# Generated by Django 3.2.25 on 2024-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_auto_20240722_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.SlugField(null=True),
        ),
    ]
