# Generated by Django 3.2.25 on 2024-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_auto_20240729_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='thing',
            name='visible',
            field=models.CharField(default='u', max_length=2),
        ),
    ]
