# Generated by Django 3.2.25 on 2024-07-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_auto_20240729_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
