# Generated by Django 3.2.25 on 2024-08-02 13:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0008_auto_20240730_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
