# Generated by Django 3.2.25 on 2024-09-24 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0010_auto_20240905_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='prefix',
            field=models.CharField(default='rfc', max_length=20),
            preserve_default=False,
        ),
    ]
